apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-eqse
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-eqse
    app.kubernetes.io/part-of: ci10t-786-0098-app
  name: devfile-sample-eqse
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-eqse
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-eqse
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0098-tenant/ci10t-786-0098-app/devfile-sample-eqse@sha256:7ee711936486cdd8a52927bd6ea84675ecd8f36759a1a3ae3c18b60496b25506
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
